"""
Brain Agent

This module defines the Brain Agent, responsible for processing and refining plans using textual and image-based inputs. It integrates stored context from a data manager to formulate logical execution steps.

The agent follows a structured approach:
1. It receives a command from the manager.
2. It considers both a text-based plan and an image-based plan.
3. It refines the plan using an LLM model and executes necessary actions.
4. It provides the final refined plan, including steps and actions taken.

"""

from utils.data_manager import DataManager  # Importing DataManager to access stored context
from vlm_agent import VLMTextAgent  # Importing VLMTextAgent for handling textual inputs
import datetime
from langchain_groq import ChatGroq
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder, PromptTemplate
from langchain_core.tools import tool
import uuid

from langchain.agents import create_react_agent, AgentExecutor
from typing import Dict, List
from pydantic import BaseModel, Field




# Define the output format for the Brain Agent's results
class BrainAgentOutput(BaseModel):
    final_answer: str = Field(..., description="The final answer to the command.")
    thoughts: List[str] = Field(..., description="List of thoughts before reaching the final answer.")
    actions_taken: List[str] = Field(..., description="List of actions executed.")



class Brain:
    def __init__(self, data_manager):
        """
        Initializes the Brain Agent.
        
        Parameters:
        - data_manager: An instance of DataManager to retrieve stored context.
        """
        self.data_manager = data_manager

        # Define available tools (functions the agent can call)
        self.tools = [tool(self.data_manager.get_store_context)]
        
        # Define the LLM model used for reasoning and plan refinement
        model_name = "llama-3.3-70b-versatile"
        self.llm = ChatGroq(
            model=model_name,
            temperature=0.0,  # Ensures deterministic responses
            max_retries=2,  # Number of retries in case of failure
        )
        
        self.agent_type = "text"  # Defines the type of agent (text-based reasoning)

        # Create the brain agent instance
        self.brain_agent = self.create_brain_agent()




    def process_plans(self, plans, command = None):
        """
        Processes the given plans and refines them into a structured execution plan.
        
        Parameters:
        - plans: Plan generated by the text-based agent. and Plan generated by the image-based agent.
        
        Returns:
        - A refined execution plan containing actions and a unique plan ID.
        """
        new_plan = self.brain_agent.invoke(
            {"previous_plans": f"{plans}", "command": command}
        )

        refined_plans = {
            "plan_id": str(uuid.uuid4()),  # Unique identifier for the plan
            "source": self.agent_type,
            "timestamp": datetime.datetime.utcnow().isoformat(),
            "actions": new_plan["output"]  # Processed actions
        }

        return refined_plans





    def create_brain_agent(self):
        """
        Creates the Brain Agent using a React-based approach to process actions and generate plans.
        
        Returns:
        - An instance of AgentExecutor for executing the agent logic.
        """
        react_template = f"""
        Answer the following questions as best you can. You have access to the following tools:

        {{tools}}
        Tools input format : 
        Use the following format:

        Question: the input question you must answer
        Thought: you should always think about what to do
        Action: the action to take, should be one of [{{tool_names}}]
        Action Input: the input to the action
        Observation: the result of the action
        ... (this Thought/Action/Action Input/Observation can repeat 2 times if needed.)
        Thought: I now know the final answer
        Final Answer: the final answer to the original input question. WHich is the Process of completetion of the task because you are brain agent.

        Return the answer to the user once completed.
        
        Begin!

        You are a brain agent and are connected with a robot. The Manager will give you a command to execute. You have to generate a thought plan on how to execute that plan. That plan was a list of completion of that plan. 

        Manager Command: {{command}}
        
        You will receive a plan from the text agent which corresponds to the Command and a plan which is sent by a robot.
        You have to make a plan for the robot how to complete the command and process the plan in realtime by seeing the store context.
        Pass each information to a robot where to go and what to do line by line.Ex like where to go which asile to go, which shelves need to check which item need to check.
        
        Plans: {{previous_plans}}

        Thought: {{agent_scratchpad}}.
        """

        # Create the local prompt template
        local_prompt = PromptTemplate(
            input_variables=["agent_scratchpad", "tool_names", "tools", "command", "previous_plans"],
            template=react_template
        )

        # Create the agent using the LLM model and defined tools
        agent_brain = create_react_agent(self.llm, self.tools, local_prompt)
        
        # Define the agent executor to handle execution
        brain_executor = AgentExecutor(
            agent=agent_brain,
            tools=self.tools,
            verbose=True,
            return_intermediate_steps=True,
            max_execution_time=None,
            max_iterations=15,  # Limit execution to 15 iterations,
            handle_parsing_errors=True
        )
        
        return brain_executor
