from vlm_agent import VLMImageAgent, VLMTextAgent
import json
from datetime import datetime

class InputModule:
    """
    The InputModule is responsible for processing commands and image inputs from the manager.
    It acts as an interface between the manager and the Brain Agent by generating a structured plan
    for execution.
    
    Responsibilities:
    - Processes text commands using the VLMTextAgent.
    - Processes image-related inputs using the VLMImageAgent.
    - Passes the generated plans to the Brain Agent for further execution.
    """
    

    def __init__(self):
        # Initialize the Vision-Language Model (VLM) agents for text and image processing
        self.VLMTextAgent = VLMTextAgent()
        self.VLMImageAgent = VLMImageAgent()


    def process_text_requests(self, cmnd: str):
        """
        Processes text-based commands received from the manager.
        
        Args:
        cmnd (str): The command string that needs to be processed.
        
        Returns:
        dict: A structured plan generated by the text agent.
        """
        plan, no_plan_executed = self.VLMTextAgent.invoke(cmnd)

        if no_plan_executed:
            msg = plan
            return msg, no_plan_executed
        
        else:
            return plan, no_plan_executed
    

    def process_image_input(self, image_path=None, image_url=None, image_bytes=None):
        """
        Processes image-based inputs along with a command from the manager.
        
        Args:
        image_path (str, optional): Local path to the image file.
        image_url (str, optional): URL of the image.
        image_bytes (bytes, optional): Raw bytes of the image.
        
        Returns:
        dict: A structured plan generated by the image agent.
        """
        plan, no_plan_executed = self.VLMImageAgent.invoke(image_path=image_path, image_url=image_url, image_bytes=image_bytes)
        
        if no_plan_executed:
            msg = plan
            return msg, no_plan_executed
        
        else:
            return plan, no_plan_executed

